# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rover_control/ControlStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ControlStatus(genpy.Message):
  _md5sum = "69100b553df4a1337bbe8ccb7c455a89"
  _type = "rover_control/ControlStatus"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int16 left_speed
int16 right_speed
int16 act1_speed
int16 act2_speed
int16 act3_speed
int16 claw_spin_speed
int16 base_speed
int16 claw_grip_speed"""
  __slots__ = ['left_speed','right_speed','act1_speed','act2_speed','act3_speed','claw_spin_speed','base_speed','claw_grip_speed']
  _slot_types = ['int16','int16','int16','int16','int16','int16','int16','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       left_speed,right_speed,act1_speed,act2_speed,act3_speed,claw_spin_speed,base_speed,claw_grip_speed

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ControlStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.left_speed is None:
        self.left_speed = 0
      if self.right_speed is None:
        self.right_speed = 0
      if self.act1_speed is None:
        self.act1_speed = 0
      if self.act2_speed is None:
        self.act2_speed = 0
      if self.act3_speed is None:
        self.act3_speed = 0
      if self.claw_spin_speed is None:
        self.claw_spin_speed = 0
      if self.base_speed is None:
        self.base_speed = 0
      if self.claw_grip_speed is None:
        self.claw_grip_speed = 0
    else:
      self.left_speed = 0
      self.right_speed = 0
      self.act1_speed = 0
      self.act2_speed = 0
      self.act3_speed = 0
      self.claw_spin_speed = 0
      self.base_speed = 0
      self.claw_grip_speed = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_8h().pack(_x.left_speed, _x.right_speed, _x.act1_speed, _x.act2_speed, _x.act3_speed, _x.claw_spin_speed, _x.base_speed, _x.claw_grip_speed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.left_speed, _x.right_speed, _x.act1_speed, _x.act2_speed, _x.act3_speed, _x.claw_spin_speed, _x.base_speed, _x.claw_grip_speed,) = _get_struct_8h().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_8h().pack(_x.left_speed, _x.right_speed, _x.act1_speed, _x.act2_speed, _x.act3_speed, _x.claw_spin_speed, _x.base_speed, _x.claw_grip_speed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.left_speed, _x.right_speed, _x.act1_speed, _x.act2_speed, _x.act3_speed, _x.claw_spin_speed, _x.base_speed, _x.claw_grip_speed,) = _get_struct_8h().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8h = None
def _get_struct_8h():
    global _struct_8h
    if _struct_8h is None:
        _struct_8h = struct.Struct("<8h")
    return _struct_8h
